/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistec.visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import sistec.bean.Empresa;
import uteis.UpperCaseLimitado;
import uteis.Uteis;

/**
 *
 * @author CASSIO JUNIOR
 */
public class EmpresaFrm extends javax.swing.JDialog {
    
    Uteis uteis = new Uteis();

    /**
     * Creates new form EmpresaControler
     */
    public EmpresaFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        jTxfRazaoSocial.setDocument(new UpperCaseLimitado(100));
        jTxfCnpj.setDocument(new UpperCaseLimitado(100));
        jTxfInscricaoEstadual.setDocument(new UpperCaseLimitado(20));
        jTxfNomeFantasia.setDocument(new UpperCaseLimitado(100));
        jTxfTelefone.setDocument(new UpperCaseLimitado(20));
        jTxfEndereco.setDocument(new UpperCaseLimitado(100));
        jTxfBairro.setDocument(new UpperCaseLimitado(50));
        jTxfQuadra.setDocument(new UpperCaseLimitado(20));
        jTxfLote.setDocument(new UpperCaseLimitado(20));
         this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "escape");
        this.getRootPane().getActionMap().put("escape", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }
    
    public void addActionListener(ActionListener listener) {
        jBtnSalvar.addActionListener(listener);
        
    }
    
    public void getEmpresa(Empresa empresa) throws Exception {
        uteis.validarJtxfield(jTxfCnpj, "Cnpj");
        uteis.validarJtxfield(jTxfRazaoSocial, "Razão Social");
        uteis.validarJtxfield(jTxfInscricaoEstadual, "Inscrição Estadual");
        uteis.validarJtxfield(jTxfNomeFantasia, "Nome Fantasia");
        empresa.setRazaoSocial(jTxfRazaoSocial.getText());
        empresa.setCnpj(jTxfCnpj.getText());
        empresa.setInscricaoEstadual(jTxfInscricaoEstadual.getText());
        empresa.setNomeFantasia(jTxfNomeFantasia.getText());
        empresa.setTelefone(jTxfTelefone.getText());
        empresa.setEndereco(jTxfEndereco.getText());
        empresa.setBairro(jTxfBairro.getText());
        empresa.setQuadra(jTxfQuadra.getText());
        empresa.setLote(jTxfLote.getText());
        empresa.setIdEmpresa(Integer.parseInt(jTxfIdEmpresa.getText()));
        
    }
    
    public void setEmpresa(Empresa empresa) {
        jTxfRazaoSocial.setText(empresa.getRazaoSocial());
        jTxfCnpj.setText(empresa.getCnpj());
        jTxfNomeFantasia.setText(empresa.getNomeFantasia());
        jTxfInscricaoEstadual.setText(empresa.getInscricaoEstadual());
        jTxfTelefone.setText(empresa.getTelefone());
        jTxfEndereco.setText(empresa.getEndereco());
        jTxfBairro.setText(empresa.getBairro());
        jTxfLote.setText(empresa.getLote());
        jTxfQuadra.setText(empresa.getQuadra());
        jTxfIdEmpresa.setText(empresa.getIdEmpresa() + "");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxfRazaoSocial = new javax.swing.JTextField();
        jTxfCnpj = new javax.swing.JTextField();
        jTxfInscricaoEstadual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxfTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxfNomeFantasia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxfBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxfQuadra = new javax.swing.JTextField();
        jTxfEndereco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxfLote = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxfIdEmpresa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jBtnSalvar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresa");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("  Cadastro de Empresa");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistec/imagens/FUNDO/BARRA DE FUNDO.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 60));

        jLabel1.setText("Razão Social");

        jLabel2.setText("CNPJ");

        jTxfRazaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfRazaoSocialKeyPressed(evt);
            }
        });

        jTxfCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfCnpjKeyPressed(evt);
            }
        });

        jTxfInscricaoEstadual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfInscricaoEstadualKeyPressed(evt);
            }
        });

        jLabel6.setText("Inscricao Estadual");

        jTxfTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfTelefoneKeyPressed(evt);
            }
        });

        jLabel7.setText("Telefone");

        jTxfNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfNomeFantasiaKeyPressed(evt);
            }
        });

        jLabel8.setText("Nome Fantasia");

        jLabel9.setText("Bairro");

        jTxfBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxfBairroActionPerformed(evt);
            }
        });
        jTxfBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfBairroKeyPressed(evt);
            }
        });

        jLabel10.setText("Qd");

        jTxfQuadra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfQuadraKeyPressed(evt);
            }
        });

        jTxfEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfEnderecoKeyPressed(evt);
            }
        });

        jLabel12.setText("Endereço");

        jTxfLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfLoteKeyPressed(evt);
            }
        });

        jLabel13.setText("LT");

        jTxfIdEmpresa.setEditable(false);
        jTxfIdEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jTxfIdEmpresa.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTxfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTxfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxfQuadra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(57, 57, 57))
                            .addComponent(jTxfLote)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jTxfIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTxfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTxfCnpj))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTxfInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTxfNomeFantasia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxfInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfQuadra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empresa", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Configuração", jPanel3);

        jBtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistec/imagens/18x18/Save.png"))); // NOI18N
        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setActionCommand("SalvarEmpresa");
        jBtnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnSalvarKeyPressed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistec/imagens/18x18/Close.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jBtnSalvar)
                .addGap(52, 52, 52)
                .addComponent(jBtnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSalvar)
                    .addComponent(jBtnCancelar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxfBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxfBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxfBairroActionPerformed

    private void jTxfRazaoSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfRazaoSocialKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTxfCnpj.requestFocus();
            
        }
    }//GEN-LAST:event_jTxfRazaoSocialKeyPressed

    private void jTxfCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfCnpjKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTxfInscricaoEstadual.requestFocus();
            
        }
    }//GEN-LAST:event_jTxfCnpjKeyPressed

    private void jTxfInscricaoEstadualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfInscricaoEstadualKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTxfNomeFantasia.requestFocus();
            
        }
    }//GEN-LAST:event_jTxfInscricaoEstadualKeyPressed

    private void jTxfNomeFantasiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfNomeFantasiaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTxfTelefone.requestFocus();
            
        }
    }//GEN-LAST:event_jTxfNomeFantasiaKeyPressed

    private void jTxfTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfTelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTxfEndereco.requestFocus();
            
        }
    }//GEN-LAST:event_jTxfTelefoneKeyPressed

    private void jTxfEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfEnderecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTxfBairro.requestFocus();
            
        }
    }//GEN-LAST:event_jTxfEnderecoKeyPressed

    private void jTxfBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfBairroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTxfQuadra.requestFocus();
            
        }
    }//GEN-LAST:event_jTxfBairroKeyPressed

    private void jTxfQuadraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfQuadraKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTxfLote.requestFocus();
            
        }
    }//GEN-LAST:event_jTxfQuadraKeyPressed

    private void jTxfLoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfLoteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBtnSalvar.requestFocus();
            
        }
    }//GEN-LAST:event_jTxfLoteKeyPressed

    private void jBtnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnSalvarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBtnSalvar.doClick();
            
        }
    }//GEN-LAST:event_jBtnSalvarKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTxfBairro;
    private javax.swing.JTextField jTxfCnpj;
    private javax.swing.JTextField jTxfEndereco;
    private javax.swing.JTextField jTxfIdEmpresa;
    private javax.swing.JTextField jTxfInscricaoEstadual;
    private javax.swing.JTextField jTxfLote;
    private javax.swing.JTextField jTxfNomeFantasia;
    private javax.swing.JTextField jTxfQuadra;
    private javax.swing.JTextField jTxfRazaoSocial;
    private javax.swing.JTextField jTxfTelefone;
    // End of variables declaration//GEN-END:variables
}
