/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistec.visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import sistec.bean.Login;
import uteis.UpperCaseLimitado;

/**
 *
 * @author CASSIO
 */
public class LoginFrm extends javax.swing.JDialog {

    Login login = new Login();

    public LoginFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTxfUsuario.setDocument(new UpperCaseLimitado(20));
        jTxfSenha.setDocument(new UpperCaseLimitado(20));
        setLocationRelativeTo(null);
         this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "escape");
        this.getRootPane().getActionMap().put("escape", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }

    public void addActionListener(ActionListener Listener) {
        jBtnSair.addActionListener(Listener);
        jBtnLogin.addActionListener(Listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxfUsuario = new javax.swing.JTextField();
        jTxfSenha = new javax.swing.JPasswordField();
        jBtnLogin = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("USUARIO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("SENHA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jTxfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTxfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 170, -1));

        jTxfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jTxfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 170, -1));

        jBtnLogin.setText("Entrar");
        jBtnLogin.setActionCommand("Login");
        jBtnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnLoginKeyPressed(evt);
            }
        });
        getContentPane().add(jBtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 80, -1));

        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistec/imagens/FUNDO/Loggin.jpeg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jTxfUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxfSenha.requestFocus();
            jTxfSenha.selectAll();
        }


    }//GEN-LAST:event_jTxfUsuarioKeyPressed

    private void jTxfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnLogin.requestFocus();
        }
    }//GEN-LAST:event_jTxfSenhaKeyPressed

    private void jBtnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnLogin.doClick();
        }
    }//GEN-LAST:event_jBtnLoginKeyPressed
    public void usuarioFocus() {
        jTxfUsuario.requestFocus();
        jTxfUsuario.selectAll();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginFrm dialog = new LoginFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPasswordField jTxfSenha;
    private javax.swing.JTextField jTxfUsuario;
    // End of variables declaration//GEN-END:variables

    public Login getLogin() {
        login.setUsuario(jTxfUsuario.getText());
        login.setSenha(jTxfSenha.getText());
        return login;

    }
}
